[package]
name = "tiny-orm-model"
version = "0.5.1"
edition = "2021"
rust-version = "1.80.0"
authors = ["Matt Delacour - mdelacour.com"]
description = "Struct and Trait avaiable for Tiny ORM. Not intended to be used directly."
license = "MIT"
repository = "https://github.com/MattDelac/tiny_orm"

[features]
default = []
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
"sqlx-0.7" = []
set-option = []
serde = ["dep:serde"]

[dependencies]
sqlx = { version = ">=0.7, <1.0", default-features = false }
serde = { version = "*", default-features = false, optional = true }

[dev-dependencies]
tokio-test = "0.4.4"
